spring:
  application:
    name: pc-component-store
  
  datasource:
    url: jdbc:mysql://localhost:3306/pc_component_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history

  security:
    jwt:
      secret: your-secret-key-here-make-it-long-and-secure-in-production
      expiration: 3600000 # 1 hour in milliseconds

app:
  jwt:
    secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
    expiration: 3600000 # 1 hour in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.onlineshop: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 